# Generated by Django 3.0.3 on 2020-09-10 11:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0025_remove_icon_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='coordinates_ele',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), null=True, size=None),
        ),
    ]
