# Generated by Django 3.0.3 on 2020-09-10 12:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0026_sequence_coordinates_ele'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ele',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
