# Generated by Django 3.0.3 on 2020-09-11 19:53

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0027_auto_20200910_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=sequence.models.image_directory_path),
        ),
    ]
